// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_API_Practice.Data;

#nullable disable

namespace REST_API_Practice.Migrations
{
    [DbContext(typeof(REST_API_Practice_Context))]
    [Migration("20250531024855_Added bok data")]
    partial class Addedbokdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REST_API_Practice.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jared Diamond",
                            ISBN = "9780143117001",
                            Title = "Collapse: How Societies Choose to Fail or Succeed",
                            YearPublished = 2011
                        },
                        new
                        {
                            Id = 2,
                            Author = "Lauren Miller",
                            ISBN = "9780062199805",
                            Title = "Free to Fall",
                            YearPublished = 2014
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jared Diamond",
                            ISBN = "9780099302780",
                            Title = "Guns, Germs, and Steel: A short history of everybody for the last 13,000 years",
                            YearPublished = 1998
                        },
                        new
                        {
                            Id = 4,
                            Author = "Gregory Kerr",
                            ISBN = "9780359434121",
                            Title = "Philosophical Phridays: Volume 1",
                            YearPublished = 2019
                        },
                        new
                        {
                            Id = 5,
                            Author = "Kautilya",
                            ISBN = "9788184750119",
                            Title = "The Arthashastra",
                            YearPublished = 2000
                        },
                        new
                        {
                            Id = 6,
                            Author = "Scott Reintgen",
                            ISBN = "9780399556821",
                            Title = "Nyxia",
                            YearPublished = 2017
                        },
                        new
                        {
                            Id = 7,
                            Author = "Claudia Gray",
                            ISBN = "9780316394031",
                            Title = "Defy the Stars",
                            YearPublished = 2017
                        },
                        new
                        {
                            Id = 8,
                            Author = "Gina Damico",
                            ISBN = "9780547822563",
                            Title = "Croak",
                            YearPublished = 2012
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
