@rootURL = http://localhost:5115

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/books/
Accept: application/json

###
GET {{rootURL}}/api/books/2/
Accept: application/json

###
POST {{rootURL}}/api/books/
Content-Type: application/json
{
  "id": 9,
  "title": "Scythe",
  "author": "Neal Shusterman",
  "yearPublished": 2018,
  "isbn": "9781406379242"
}