@rootURL = http://localhost:5115

// Default weather API
GET {{rootURL}}/weatherforecast/
Accept: application/json

###
// Get all books
GET {{rootURL}}/api/books/
Accept: application/json

###
// Get book by ID
GET {{rootURL}}/api/books/3/
Accept: application/json

###
// Add new book to list
POST {{rootURL}}/api/books/
Content-Type: application/json
{
  "title": "Free to Fall",
  "author": "Lauren Miller",
  "yearPublished": 2014,
  "isbn": "9780062199805"
}

###
// Update book by ID
PUT {{rootURL}}/api/books/2/
Content-Type: application/json
{
  "id": 2,
  "title": "Free to Fall",
  "author": "Lauren Miller",
  "yearPublished": 2014,
  "isbn": "9780062199805"
}

###
// Delete book by ID
DELETE {{rootURL}}/api/books/2/
Accept: application/json